# -*- coding: utf-8 -*-
"""execute.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11zwCpIm0Iespe5DkTOwxFhGV5yqjEKbG
"""

import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.0.0-bin-hadoop3.2"
# install findspark using pip

import config_projet

def execute(chemin,Nom):
  data = config_projet.lire_data(chemin)
  config_projet.predictPriceClosing(data,Nom)

def main(chemin,Nom):
    execute(chemin,Nom)
if __name__ == "__main__":
    main()