# -*- coding: utf-8 -*-
"""Projet_NadiaOUACIF.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ty9r7Hm7IFdKNcxQosfcuZ0aKJ4DqdnZ
"""

# innstall java
!apt-get install openjdk-8-jdk-headless -qq > /dev/null
# install spark (change the version number if needed)
!wget -q https://archive.apache.org/dist/spark/spark-3.0.0/spark-3.0.0-bin-hadoop3.2.tgz
# unzip the spark file to the current folder
!tar xf spark-3.0.0-bin-hadoop3.2.tgz

!pip install -q findspark
!pip install library
!apt-get install library

import execute

execute.main("/content/preprocessed_CAC40.csv",'Hermès (Hermes International')



